// Copyright The prometheus-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
	monitoringv1 "github.com/prometheus-operator/prometheus-operator/pkg/client/applyconfiguration/monitoring/v1"
	scheme "github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SLSPodMonitorsGetter has a method to return a SLSPodMonitorInterface.
// A group's client should implement this interface.
type SLSPodMonitorsGetter interface {
	SLSPodMonitors(namespace string) SLSPodMonitorInterface
}

// SLSPodMonitorInterface has methods to work with SLSPodMonitor resources.
type SLSPodMonitorInterface interface {
	Create(ctx context.Context, sLSPodMonitor *v1.SLSPodMonitor, opts metav1.CreateOptions) (*v1.SLSPodMonitor, error)
	Update(ctx context.Context, sLSPodMonitor *v1.SLSPodMonitor, opts metav1.UpdateOptions) (*v1.SLSPodMonitor, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.SLSPodMonitor, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.SLSPodMonitorList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SLSPodMonitor, err error)
	Apply(ctx context.Context, sLSPodMonitor *monitoringv1.SLSPodMonitorApplyConfiguration, opts metav1.ApplyOptions) (result *v1.SLSPodMonitor, err error)
	SLSPodMonitorExpansion
}

// sLSPodMonitors implements SLSPodMonitorInterface
type sLSPodMonitors struct {
	client rest.Interface
	ns     string
}

// newSLSPodMonitors returns a SLSPodMonitors
func newSLSPodMonitors(c *MonitoringV1Client, namespace string) *sLSPodMonitors {
	return &sLSPodMonitors{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the sLSPodMonitor, and returns the corresponding sLSPodMonitor object, and an error if there is any.
func (c *sLSPodMonitors) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.SLSPodMonitor, err error) {
	result = &v1.SLSPodMonitor{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("slspodmonitors").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SLSPodMonitors that match those selectors.
func (c *sLSPodMonitors) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SLSPodMonitorList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SLSPodMonitorList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("slspodmonitors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sLSPodMonitors.
func (c *sLSPodMonitors) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("slspodmonitors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a sLSPodMonitor and creates it.  Returns the server's representation of the sLSPodMonitor, and an error, if there is any.
func (c *sLSPodMonitors) Create(ctx context.Context, sLSPodMonitor *v1.SLSPodMonitor, opts metav1.CreateOptions) (result *v1.SLSPodMonitor, err error) {
	result = &v1.SLSPodMonitor{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("slspodmonitors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sLSPodMonitor).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a sLSPodMonitor and updates it. Returns the server's representation of the sLSPodMonitor, and an error, if there is any.
func (c *sLSPodMonitors) Update(ctx context.Context, sLSPodMonitor *v1.SLSPodMonitor, opts metav1.UpdateOptions) (result *v1.SLSPodMonitor, err error) {
	result = &v1.SLSPodMonitor{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("slspodmonitors").
		Name(sLSPodMonitor.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sLSPodMonitor).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the sLSPodMonitor and deletes it. Returns an error if one occurs.
func (c *sLSPodMonitors) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("slspodmonitors").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sLSPodMonitors) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("slspodmonitors").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched sLSPodMonitor.
func (c *sLSPodMonitors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SLSPodMonitor, err error) {
	result = &v1.SLSPodMonitor{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("slspodmonitors").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied sLSPodMonitor.
func (c *sLSPodMonitors) Apply(ctx context.Context, sLSPodMonitor *monitoringv1.SLSPodMonitorApplyConfiguration, opts metav1.ApplyOptions) (result *v1.SLSPodMonitor, err error) {
	if sLSPodMonitor == nil {
		return nil, fmt.Errorf("sLSPodMonitor provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(sLSPodMonitor)
	if err != nil {
		return nil, err
	}
	name := sLSPodMonitor.Name
	if name == nil {
		return nil, fmt.Errorf("sLSPodMonitor.Name must be provided to Apply")
	}
	result = &v1.SLSPodMonitor{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("slspodmonitors").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
