// Copyright The prometheus-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
	monitoringv1 "github.com/prometheus-operator/prometheus-operator/pkg/client/applyconfiguration/monitoring/v1"
	scheme "github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SLSServiceMonitorsGetter has a method to return a SLSServiceMonitorInterface.
// A group's client should implement this interface.
type SLSServiceMonitorsGetter interface {
	SLSServiceMonitors(namespace string) SLSServiceMonitorInterface
}

// SLSServiceMonitorInterface has methods to work with SLSServiceMonitor resources.
type SLSServiceMonitorInterface interface {
	Create(ctx context.Context, sLSServiceMonitor *v1.SLSServiceMonitor, opts metav1.CreateOptions) (*v1.SLSServiceMonitor, error)
	Update(ctx context.Context, sLSServiceMonitor *v1.SLSServiceMonitor, opts metav1.UpdateOptions) (*v1.SLSServiceMonitor, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.SLSServiceMonitor, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.SLSServiceMonitorList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SLSServiceMonitor, err error)
	Apply(ctx context.Context, sLSServiceMonitor *monitoringv1.SLSServiceMonitorApplyConfiguration, opts metav1.ApplyOptions) (result *v1.SLSServiceMonitor, err error)
	SLSServiceMonitorExpansion
}

// sLSServiceMonitors implements SLSServiceMonitorInterface
type sLSServiceMonitors struct {
	client rest.Interface
	ns     string
}

// newSLSServiceMonitors returns a SLSServiceMonitors
func newSLSServiceMonitors(c *MonitoringV1Client, namespace string) *sLSServiceMonitors {
	return &sLSServiceMonitors{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the sLSServiceMonitor, and returns the corresponding sLSServiceMonitor object, and an error if there is any.
func (c *sLSServiceMonitors) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.SLSServiceMonitor, err error) {
	result = &v1.SLSServiceMonitor{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("slsservicemonitors").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SLSServiceMonitors that match those selectors.
func (c *sLSServiceMonitors) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SLSServiceMonitorList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SLSServiceMonitorList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("slsservicemonitors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sLSServiceMonitors.
func (c *sLSServiceMonitors) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("slsservicemonitors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a sLSServiceMonitor and creates it.  Returns the server's representation of the sLSServiceMonitor, and an error, if there is any.
func (c *sLSServiceMonitors) Create(ctx context.Context, sLSServiceMonitor *v1.SLSServiceMonitor, opts metav1.CreateOptions) (result *v1.SLSServiceMonitor, err error) {
	result = &v1.SLSServiceMonitor{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("slsservicemonitors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sLSServiceMonitor).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a sLSServiceMonitor and updates it. Returns the server's representation of the sLSServiceMonitor, and an error, if there is any.
func (c *sLSServiceMonitors) Update(ctx context.Context, sLSServiceMonitor *v1.SLSServiceMonitor, opts metav1.UpdateOptions) (result *v1.SLSServiceMonitor, err error) {
	result = &v1.SLSServiceMonitor{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("slsservicemonitors").
		Name(sLSServiceMonitor.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sLSServiceMonitor).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the sLSServiceMonitor and deletes it. Returns an error if one occurs.
func (c *sLSServiceMonitors) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("slsservicemonitors").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sLSServiceMonitors) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("slsservicemonitors").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched sLSServiceMonitor.
func (c *sLSServiceMonitors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SLSServiceMonitor, err error) {
	result = &v1.SLSServiceMonitor{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("slsservicemonitors").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied sLSServiceMonitor.
func (c *sLSServiceMonitors) Apply(ctx context.Context, sLSServiceMonitor *monitoringv1.SLSServiceMonitorApplyConfiguration, opts metav1.ApplyOptions) (result *v1.SLSServiceMonitor, err error) {
	if sLSServiceMonitor == nil {
		return nil, fmt.Errorf("sLSServiceMonitor provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(sLSServiceMonitor)
	if err != nil {
		return nil, err
	}
	name := sLSServiceMonitor.Name
	if name == nil {
		return nil, fmt.Errorf("sLSServiceMonitor.Name must be provided to Apply")
	}
	result = &v1.SLSServiceMonitor{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("slsservicemonitors").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
