// Copyright The prometheus-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	monitoringv1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
	applyconfigurationmonitoringv1 "github.com/prometheus-operator/prometheus-operator/pkg/client/applyconfiguration/monitoring/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSLSPodMonitors implements SLSPodMonitorInterface
type FakeSLSPodMonitors struct {
	Fake *FakeMonitoringV1
	ns   string
}

var slspodmonitorsResource = schema.GroupVersionResource{Group: "monitoring.coreos.com", Version: "v1", Resource: "slspodmonitors"}

var slspodmonitorsKind = schema.GroupVersionKind{Group: "monitoring.coreos.com", Version: "v1", Kind: "SLSPodMonitor"}

// Get takes name of the sLSPodMonitor, and returns the corresponding sLSPodMonitor object, and an error if there is any.
func (c *FakeSLSPodMonitors) Get(ctx context.Context, name string, options v1.GetOptions) (result *monitoringv1.SLSPodMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(slspodmonitorsResource, c.ns, name), &monitoringv1.SLSPodMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*monitoringv1.SLSPodMonitor), err
}

// List takes label and field selectors, and returns the list of SLSPodMonitors that match those selectors.
func (c *FakeSLSPodMonitors) List(ctx context.Context, opts v1.ListOptions) (result *monitoringv1.SLSPodMonitorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(slspodmonitorsResource, slspodmonitorsKind, c.ns, opts), &monitoringv1.SLSPodMonitorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &monitoringv1.SLSPodMonitorList{ListMeta: obj.(*monitoringv1.SLSPodMonitorList).ListMeta}
	for _, item := range obj.(*monitoringv1.SLSPodMonitorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sLSPodMonitors.
func (c *FakeSLSPodMonitors) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(slspodmonitorsResource, c.ns, opts))

}

// Create takes the representation of a sLSPodMonitor and creates it.  Returns the server's representation of the sLSPodMonitor, and an error, if there is any.
func (c *FakeSLSPodMonitors) Create(ctx context.Context, sLSPodMonitor *monitoringv1.SLSPodMonitor, opts v1.CreateOptions) (result *monitoringv1.SLSPodMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(slspodmonitorsResource, c.ns, sLSPodMonitor), &monitoringv1.SLSPodMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*monitoringv1.SLSPodMonitor), err
}

// Update takes the representation of a sLSPodMonitor and updates it. Returns the server's representation of the sLSPodMonitor, and an error, if there is any.
func (c *FakeSLSPodMonitors) Update(ctx context.Context, sLSPodMonitor *monitoringv1.SLSPodMonitor, opts v1.UpdateOptions) (result *monitoringv1.SLSPodMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(slspodmonitorsResource, c.ns, sLSPodMonitor), &monitoringv1.SLSPodMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*monitoringv1.SLSPodMonitor), err
}

// Delete takes name of the sLSPodMonitor and deletes it. Returns an error if one occurs.
func (c *FakeSLSPodMonitors) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(slspodmonitorsResource, c.ns, name, opts), &monitoringv1.SLSPodMonitor{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSLSPodMonitors) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(slspodmonitorsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &monitoringv1.SLSPodMonitorList{})
	return err
}

// Patch applies the patch and returns the patched sLSPodMonitor.
func (c *FakeSLSPodMonitors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *monitoringv1.SLSPodMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(slspodmonitorsResource, c.ns, name, pt, data, subresources...), &monitoringv1.SLSPodMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*monitoringv1.SLSPodMonitor), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied sLSPodMonitor.
func (c *FakeSLSPodMonitors) Apply(ctx context.Context, sLSPodMonitor *applyconfigurationmonitoringv1.SLSPodMonitorApplyConfiguration, opts v1.ApplyOptions) (result *monitoringv1.SLSPodMonitor, err error) {
	if sLSPodMonitor == nil {
		return nil, fmt.Errorf("sLSPodMonitor provided to Apply must not be nil")
	}
	data, err := json.Marshal(sLSPodMonitor)
	if err != nil {
		return nil, err
	}
	name := sLSPodMonitor.Name
	if name == nil {
		return nil, fmt.Errorf("sLSPodMonitor.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(slspodmonitorsResource, c.ns, *name, types.ApplyPatchType, data), &monitoringv1.SLSPodMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*monitoringv1.SLSPodMonitor), err
}
